services:
  ufw-gui:
    image: webyhomelab/ufw-gui:latest
    container_name: ufw-gui
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/Kyiv
      - UFW_GUI_SECRET_KEY=change_me_to_a_secure_random_string_123
    volumes:
      - ./data:/app/data
      - /etc/ufw:/etc/ufw
      - /var/run/fail2ban/fail2ban.sock:/var/run/fail2ban/fail2ban.sock
      - /var/log:/var/log:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
